name: peaces_madagascar_tours
description: A tourism application for Madagascar
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts:
  clean: "flutter clean && flutter pub get --no-offline"
  deploy: "flutter build web --release && firebase deploy"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_route: ^9.3.0+1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  url_launcher: ^6.3.0
  flutter_seo: ^1.1.1
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/baobab.png
    - assets/flight.png
    - assets/arrow.png
    - assets/images/
    - assets/logos/
