name: peaces_madagascar_tours
description: A tourism application for Madagascar
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts:
  clean: "flutter clean && flutter pub get --no-offline"
  deploy: "flutter build web --release && firebase deploy"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^9.0.0
  auto_route: ^9.3.0+1
  get_it: ^8.0.3
  injectable: ^2.3.2
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_core: ^3.8.0
  firebase_data_connect: ^0.1.2+4
  ussd_service: ^0.1.1
  ussd_advanced: ^1.1.0
  ussd_launcher: ^1.2.8
  url_launcher: ^6.3.0
  gh_pages: ^0.1.1
  flutter_seo: ^1.1.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.4.1
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/baobab.png
    - assets/flight.png
    - assets/images/
    - assets/logos/
